'''
No. project: 4
Name project: Rock, Paper, Scissors Game
Description: This is a paper, scissors, rock game created using conditionals and random module in Python where
             player's choice selects his state through typing it and choice from computer is generated by means of random numbers.
Author: Jonathan Eduardo Castilla Zamora
'''


import random # Import random module for generating aleatory numbers

# ASCII art in order to represent the different states involves during the game
# Implementing a dictionary
game_states = {
"rock":'''
    _______
---'   ____)
      (_____)
      (_____)
      (____)
---.__(___)
''',

"paper":'''
    _______
---'   ____)____
          ______)
          _______)
         _______)
---.__________)
''',

"scissors":'''
    _______
---'   ____)____
          ______)
       __________)
      (____)
---.__(___)
'''}

print("Welcome to the Rock - Paper - Scissors Game!") # Print a greeting message

# Obtaining the choice from player and printing it
list_game_states = ['rock', 'paper', 'scissors']
player_choice = str(input("Firstly, What do you choose? Type 'Rock', 'Paper' or 'Scissors': ")).lower()

# Verifying that player has chosen a correct state's game for playing with the computer
if player_choice in list_game_states:
    print("You chose: " + game_states[player_choice])
    # By means of random module we can generate the choice from computer and printing it
    computer_choice = random.choice(['rock', 'paper', 'scissors'])
    print(f"Computer chose: {computer_choice.title()}")
    print(game_states[computer_choice])

    # The logic behind Rock - Paper - Scissors Game
    if computer_choice == player_choice:
        print("It's a tie!")
    elif computer_choice == 'rock' and player_choice == 'scissors' or computer_choice == 'scissors' and player_choice == 'paper' or computer_choice == 'paper' and player_choice == 'rock':
        print("Computer wins!")
    else:
        print("You win!")
else:
    print("Sorry, that's not a right choice.")

